"""live chat + comment retry fields

Revision ID: 30d22d787999
Revises: e78025a32c66
Create Date: 2026-06-03 23:20:35.286930
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d22d787999'
down_revision: Union[str, None] = 'e78025a32c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # NOT NULL columns added to existing tables need a server_default so rows
    # already present get a value (portable across SQLite and PostgreSQL).
    op.add_column('live_chat_messages', sa.Column('time_text', sa.String(length=32), nullable=True))
    op.add_column('live_chat_messages', sa.Column('amount_text', sa.String(length=64), nullable=True))
    op.add_column('live_chat_messages', sa.Column('message_type', sa.String(length=32), nullable=True))
    op.add_column('live_chat_messages', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('live_chat_messages', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    op.add_column('live_chat_messages', sa.Column('is_deleted_or_missing', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('videos', sa.Column('comment_refresh_failures', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('videos', sa.Column('last_live_chat_refresh_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('next_live_chat_refresh_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('live_chat_state', sa.String(length=32), nullable=True))
    op.add_column('videos', sa.Column('has_live_chat', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_videos_next_live_chat_refresh_at'), 'videos', ['next_live_chat_refresh_at'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_next_live_chat_refresh_at'), table_name='videos')
    op.drop_column('videos', 'has_live_chat')
    op.drop_column('videos', 'live_chat_state')
    op.drop_column('videos', 'next_live_chat_refresh_at')
    op.drop_column('videos', 'last_live_chat_refresh_at')
    op.drop_column('videos', 'comment_refresh_failures')
    op.drop_column('live_chat_messages', 'is_deleted_or_missing')
    op.drop_column('live_chat_messages', 'fetched_at')
    op.drop_column('live_chat_messages', 'published_at')
    op.drop_column('live_chat_messages', 'message_type')
    op.drop_column('live_chat_messages', 'amount_text')
    op.drop_column('live_chat_messages', 'time_text')
    # ### end Alembic commands ###
