"""liked_videos

Revision ID: b4c1b3203886
Revises: 30d22d787999
Create Date: 2026-06-05 00:58:17.295353
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c1b3203886'
down_revision: Union[str, None] = '30d22d787999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('channel_title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('liked_at', sa.DateTime(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'youtube_video_id', name='uq_liked_video')
    )
    op.create_index(op.f('ix_liked_videos_source'), 'liked_videos', ['source'], unique=False)
    op.create_index(op.f('ix_liked_videos_video_id'), 'liked_videos', ['video_id'], unique=False)
    op.create_index(op.f('ix_liked_videos_youtube_video_id'), 'liked_videos', ['youtube_video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liked_videos_youtube_video_id'), table_name='liked_videos')
    op.drop_index(op.f('ix_liked_videos_video_id'), table_name='liked_videos')
    op.drop_index(op.f('ix_liked_videos_source'), table_name='liked_videos')
    op.drop_table('liked_videos')
    # ### end Alembic commands ###
