"""initial schema

Revision ID: d5645fa4224d
Revises: 
Create Date: 2026-06-02 21:42:03.394611
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5645fa4224d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('markdown', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('source_event_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_date'), 'diary_entries', ['date'], unique=False)
    op.create_table('download_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('media_mode', sa.String(length=16), nullable=False),
    sa.Column('quality_mode', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ytdlp_args', sa.JSON(), nullable=False),
    sa.Column('ffmpeg_args', sa.JSON(), nullable=False),
    sa.Column('metadata_flags', sa.JSON(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_profiles_name'), 'download_profiles', ['name'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('api_source', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_type'), 'sources', ['type'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('channel_title', sa.String(length=512), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('upload_date', sa.String(length=8), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_short', sa.Boolean(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_metadata_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('raw_info_json_path', sa.Text(), nullable=True),
    sa.Column('comments_refresh_policy', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_channel_id'), 'videos', ['channel_id'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    op.create_table('watch_history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('channel_title', sa.String(length=512), nullable=True),
    sa.Column('watched_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_history_events_youtube_video_id'), 'watch_history_events', ['youtube_video_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('youtube_playlist_id', sa.String(length=64), nullable=True),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('crawl_policy', sa.String(length=32), nullable=True),
    sa.Column('download_profile_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['download_profile_id'], ['download_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_source_id'), 'collections', ['source_id'], unique=False)
    op.create_index(op.f('ix_collections_type'), 'collections', ['type'], unique=False)
    op.create_table('live_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp_ms', sa.BigInteger(), nullable=True),
    sa.Column('author_name', sa.String(length=512), nullable=True),
    sa.Column('author_channel_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('badges', sa.JSON(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('is_superchat', sa.Boolean(), nullable=False),
    sa.Column('is_member_message', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'message_id', name='uq_video_chatmsg')
    )
    op.create_index(op.f('ix_live_chat_messages_video_id'), 'live_chat_messages', ['video_id'], unique=False)
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('profile', sa.String(length=64), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('container', sa.String(length=16), nullable=True),
    sa.Column('codec_video', sa.String(length=32), nullable=True),
    sa.Column('codec_audio', sa.String(length=32), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('filesize', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_video_id'), 'media_files', ['video_id'], unique=False)
    op.create_table('metadata_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('snapshot_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metadata_snapshots_video_id'), 'metadata_snapshots', ['video_id'], unique=False)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('is_auto', sa.Boolean(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=32), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'video_id', name='uq_collection_video')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_video_id'), 'collection_items', ['video_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.String(length=128), nullable=False),
    sa.Column('parent_comment_id', sa.String(length=128), nullable=True),
    sa.Column('author_name', sa.String(length=512), nullable=True),
    sa.Column('author_channel_id', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted_or_missing', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['metadata_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', 'comment_id', name='uq_video_comment')
    )
    op.create_index(op.f('ix_comments_video_id'), 'comments', ['video_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(length=64), nullable=True),
    sa.Column('parent_job_id', sa.Integer(), nullable=True),
    sa.Column('rq_job_id', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('command_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['download_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_comments_video_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_collection_items_video_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_metadata_snapshots_video_id'), table_name='metadata_snapshots')
    op.drop_table('metadata_snapshots')
    op.drop_index(op.f('ix_media_files_video_id'), table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_live_chat_messages_video_id'), table_name='live_chat_messages')
    op.drop_table('live_chat_messages')
    op.drop_index(op.f('ix_collections_type'), table_name='collections')
    op.drop_index(op.f('ix_collections_source_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_watch_history_events_youtube_video_id'), table_name='watch_history_events')
    op.drop_table('watch_history_events')
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_channel_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_sources_type'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_download_profiles_name'), table_name='download_profiles')
    op.drop_table('download_profiles')
    op.drop_index(op.f('ix_diary_entries_date'), table_name='diary_entries')
    op.drop_table('diary_entries')
    # ### end Alembic commands ###
