"""video comment refresh fields

Revision ID: e78025a32c66
Revises: f7119e06da9e
Create Date: 2026-06-03 10:39:56.351002
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78025a32c66'
down_revision: Union[str, None] = 'f7119e06da9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('last_comments_refresh_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('next_comments_refresh_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('comments_state', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_videos_next_comments_refresh_at'), 'videos', ['next_comments_refresh_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_next_comments_refresh_at'), table_name='videos')
    op.drop_column('videos', 'comments_state')
    op.drop_column('videos', 'next_comments_refresh_at')
    op.drop_column('videos', 'last_comments_refresh_at')
    # ### end Alembic commands ###
