"""add search_history_events

Revision ID: f7119e06da9e
Revises: 4c065fed63a9
Create Date: 2026-06-03 09:58:31.712337
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7119e06da9e'
down_revision: Union[str, None] = '4c065fed63a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('query', sa.String(length=512), nullable=True),
    sa.Column('searched_at', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'query', 'searched_at', name='uq_search_event')
    )
    op.create_index(op.f('ix_search_history_events_source'), 'search_history_events', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_events_source'), table_name='search_history_events')
    op.drop_table('search_history_events')
    # ### end Alembic commands ###
