#!/usr/bin/env python3
"""Phase 10A.1: generate a hash-pinned Python lock from a known-good freeze.

Input:  a `pip freeze` of the known-good release image (every runtime package
        pinned `name==version`, editable project excluded).
Output: `requirements.lock` where every package is `name==version` with ALL of
        that version's PyPI file sha256 hashes (`--hash=sha256:...`), so
        `pip install --require-hashes -r requirements.lock` is reproducible and
        tamper-evident.

It does NOT resolve or upgrade anything — it pins EXACTLY the input versions and
only fetches their hashes from PyPI. Fail-closed: any package/version whose
hashes cannot be fetched aborts the whole file (no partial lock).

usage: scripts/gen-python-lock.py <freeze.txt> <out.lock> [--source "<desc>"]
"""

from __future__ import annotations

import json
import sys
import urllib.request

PYPI = "https://pypi.org/pypi/{name}/{version}/json"


def fetch_hashes(name: str, version: str) -> list[str]:
    url = PYPI.format(name=name, version=version)
    with urllib.request.urlopen(url, timeout=30) as r:  # noqa: S310 - pinned host
        data = json.load(r)
    files = data.get("urls") or []
    digests = sorted({f["digests"]["sha256"] for f in files
                      if f.get("digests", {}).get("sha256")})
    if not digests:
        raise RuntimeError(f"{name}=={version}: no sha256 digests on PyPI")
    return digests


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(2)
    freeze_path, out_path = sys.argv[1], sys.argv[2]
    source = "known-good release image freeze"
    if "--source" in sys.argv:
        source = sys.argv[sys.argv.index("--source") + 1]

    pins: list[tuple[str, str]] = []
    for line in open(freeze_path, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-e "):
            continue
        if "==" not in line:
            print(f"refusing non-pinned line: {line}")
            sys.exit(1)
        name, version = line.split("==", 1)
        pins.append((name.strip(), version.strip().split(";")[0].strip()))

    lines = [
        "# requirements.lock — Phase 10A.1 hash-pinned Python lock.",
        f"# Source: {source}",
        "# Generated by scripts/gen-python-lock.py from the exact known-good",
        "# versions (NO re-resolution / upgrade). Install with:",
        "#   pip install --require-hashes -r requirements.lock",
        f"# Packages: {len(pins)}",
        "",
    ]
    for name, version in sorted(pins, key=lambda p: p[0].lower()):
        digests = fetch_hashes(name, version)
        hashline = " \\\n    ".join(f"--hash=sha256:{h}" for h in digests)
        lines.append(f"{name}=={version} \\\n    {hashline}")
    open(out_path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"wrote {out_path}: {len(pins)} packages, hash-pinned")


if __name__ == "__main__":
    main()
